# Generated by Django 3.0.2 on 2020-02-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_merge_20200204_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Status',
        ),
    ]
