# Generated by Django 3.0.2 on 2020-02-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_remove_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived')], default='active', max_length=20, null=True),
        ),
    ]
