# Generated by Django 2.0.7 on 2020-02-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Status',
        ),
    ]
