# Generated by Django 2.0.7 on 2020-02-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_remove_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived')], default='active', max_length=20, null=True),
        ),
    ]
