# Generated by Django 2.0.7 on 2020-02-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0006_answer_text'),
        ('Question', '0004_auto_20200206_1043'),
        ('Question', '0004_auto_20200206_1117'),
    ]

    operations = [
    ]
