# Generated by Django 3.0.2 on 2020-02-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0004_auto_20200206_1043'),
        ('Question', '0007_merge_20200206_2150'),
    ]

    operations = [
    ]
