# Generated by Django 3.0.2 on 2020-02-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0008_merge_20200206_2251'),
        ('Question', '0007_merge_20200207_0220'),
    ]

    operations = [
    ]
