# Generated by Django 3.0.2 on 2020-02-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0009_merge_20200206_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
