# Generated by Django 3.0.2 on 2020-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0010_choice_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.TextField(default='No Default'),
        ),
    ]
