# Generated by Django 3.0.2 on 2020-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0011_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.TextField(default='No Default', max_length=27),
        ),
    ]
