# Generated by Django 3.0.2 on 2020-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0012_auto_20200207_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.TextField(default='No Default', max_length=24),
        ),
    ]
