# Generated by Django 2.1.5 on 2020-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Activated',
            field=models.BooleanField(default=True),
        ),
    ]
