# Generated by Django 3.0.2 on 2020-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0005_answer'),
        ('Student', '0002_student_selectedchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='LongAnswers',
            field=models.ManyToManyField(blank=True, null=True, to='Question.Answer'),
        ),
    ]
