# Generated by Django 2.0.7 on 2020-02-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_longanswers'),
        ('Student', '0003_student_verifycode'),
    ]

    operations = [
    ]
