# Generated by Django 3.0.2 on 2020-02-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_longanswers'),
        ('Student', '0003_student_verifycode'),
    ]

    operations = [
    ]
